# Generated by Django 2.2.6 on 2020-05-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'quiz_event',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=512)),
                ('quiz_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Event')),
            ],
            options={
                'db_table': 'quiz_section',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('points_per_item', models.IntegerField(max_length=3)),
                ('quiz_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Section')),
            ],
            options={
                'db_table': 'quiz_question',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1024)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Question')),
            ],
            options={
                'db_table': 'quiz_choices',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Choices')),
            ],
            options={
                'db_table': 'quiz_answer',
            },
        ),
    ]
