# Generated by Django 2.2.6 on 2020-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='points_per_item',
        ),
        migrations.AddField(
            model_name='quiz_section',
            name='points_per_item',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_section',
            name='instruction',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
