# Generated by Django 2.2.6 on 2020-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200520_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_choices',
            name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz_section',
        ),
        migrations.RemoveField(
            model_name='quiz_section',
            name='quiz_event',
        ),
        migrations.AddField(
            model_name='quiz_event',
            name='quiz_section',
            field=models.ManyToManyField(blank=True, to='app.Quiz_Section'),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='quiz_answer',
            field=models.ManyToManyField(blank=True, to='app.Quiz_Answer'),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='quiz_choices',
            field=models.ManyToManyField(blank=True, to='app.Quiz_Choices'),
        ),
        migrations.AddField(
            model_name='quiz_section',
            name='quiz_question',
            field=models.ManyToManyField(blank=True, to='app.Quiz_Question'),
        ),
        migrations.AlterField(
            model_name='quiz_section',
            name='points_per_item',
            field=models.IntegerField(null=True),
        ),
    ]
