# Generated by Django 2.2.6 on 2020-05-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200520_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz_answer',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='quiz_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Answer'),
        ),
    ]
