# Generated by Django 2.2.6 on 2020-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_quiz_section_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_section',
            name='quiz_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
