# Generated by Django 2.2.6 on 2020-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quiz_section_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
