# Generated by Django 2.2.6 on 2020-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200521_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_answer',
            name='quiz_answer',
            field=models.CharField(max_length=128),
        ),
    ]
